<a href="https://colab.research.google.com/github/lorek/MethodsClassDimRed/blob/main/MoCaDR_List_nr_10_Bag_of_Words_Word2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bag of words and Word2Vec

In [1]:
# Paweł Lorek
import numpy as np
import time
import gensim

from gensim.models import Word2Vec

import nltk
from nltk.corpus import brown, movie_reviews, treebank


from gensim.models import KeyedVectors
import string
from nltk.stem import PorterStemmer
from nltk import word_tokenize
from nltk.corpus import brown

from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer  # TF-IDF

from sklearn.metrics.pairwise import cosine_similarity


## Bag of Words

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [35]:
documents = [
    "The quick brown fox jumped over the lazy dog.",
    "The dog slept in the afternoon.",
    "Foxes are wild animals.",
    "Dogs are loyal pets."
]

In [36]:
# Convert texts to count vectors
count_vect = CountVectorizer()
X_counts = count_vect.fit_transform(documents)

# Display count vectors
print("Count Vectors (CountVectorizer):")
print(X_counts.toarray())
print("\nVocabulary:", count_vect.get_feature_names_out())

# Convert count vectors to tf-idf vectors
tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit_transform(X_counts)

# Display tf-idf vectors
print("\nTF-IDF Vectors (TfidfTransformer):")
print(X_tfidf.toarray())

Count Vectors (CountVectorizer):
[[0 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 2 0]
 [1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 2 0]
 [0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0]]

Vocabulary: ['afternoon' 'animals' 'are' 'brown' 'dog' 'dogs' 'fox' 'foxes' 'in'
 'jumped' 'lazy' 'loyal' 'over' 'pets' 'quick' 'slept' 'the' 'wild']

TF-IDF Vectors (TfidfTransformer):
[[0.         0.         0.         0.33135182 0.26124158 0.
  0.33135182 0.         0.         0.33135182 0.33135182 0.
  0.33135182 0.         0.33135182 0.         0.52248316 0.        ]
 [0.40462414 0.         0.         0.         0.31901032 0.
  0.         0.         0.40462414 0.         0.         0.
  0.         0.         0.         0.40462414 0.63802064 0.        ]
 [0.         0.52547275 0.41428875 0.         0.         0.
  0.         0.52547275 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.52547275]
 [0.         0.         0.41428875 0.         0.        

# Word2Vec:  train model from gensim

In [2]:
nltk.download('brown')
nltk.download('treebank')


[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.


True

In [3]:
print("Calculating Word2Vec for 'brown' dataset .", end="", flush=True)
start_time = time.time()
w2v_brown = Word2Vec(brown.sents())
print("\t\t took %s seconds " % round((time.time() - start_time),5))

Calculating Word2Vec for 'brown' dataset .		 took 41.83131 seconds 


In [4]:
print("Calculating Word2Vec for 'treebank' dataset .", end="", flush=True)
start_time = time.time()
w2v_tb = Word2Vec(treebank.sents())
print("\t\t took %s seconds " % round((time.time() - start_time),5))

Calculating Word2Vec for 'treebank' dataset .		 took 6.99281 seconds 


In [5]:
print("dimension: ", len(w2v_brown.wv["apple"] ), " apple = ",w2v_brown.wv["apple"] )

dimension:  100  apple =  [ 8.23317096e-02  7.47319683e-02  2.82908306e-02 -1.21446997e-02
 -1.04962839e-02 -6.36102557e-02  7.00236708e-02  1.68403789e-01
 -9.15719345e-02 -6.93530589e-02  2.52947379e-02 -7.26555213e-02
  3.64574529e-02  1.87692493e-02  6.36409223e-02 -8.40146691e-02
  2.57701166e-02 -4.56809811e-02 -6.15098029e-02 -1.15827225e-01
  5.14591821e-02 -3.46797146e-02  7.93560594e-02  3.59990099e-03
 -2.32398231e-02 -6.20469041e-02 -5.70676811e-02 -3.26855630e-02
 -3.14676575e-02  5.08689173e-02  1.10364281e-01 -8.83811116e-02
  1.91504788e-02 -1.15050547e-01  1.25137437e-02  6.65299371e-02
 -8.86415783e-03 -2.57209074e-02 -3.10990419e-02 -5.99632487e-02
  1.54627804e-02 -1.06639534e-01  5.33831678e-02  7.78012797e-02
  5.69414236e-02 -3.42835225e-02 -1.56059917e-02  2.07771473e-02
 -1.03374105e-03  6.17487319e-02  2.11441424e-02 -8.66596252e-02
 -5.05734272e-02 -5.78068383e-02 -5.20443767e-02 -4.67707328e-02
  8.93955827e-02  3.30981053e-02 -1.18302228e-02  1.55865634e-02

In [6]:
sample_words = ["apple","pear","car","house","building"]

for w1 in sample_words:
  for w2 in sample_words:

    print("w1=",w1,", w2=",w2,"\t\t\t brown: cosine_similarity(w1,w2) = ", cosine_similarity([w2v_brown.wv[w1]],[w2v_brown.wv[w2]]))

w1= apple , w2= apple 			 brown: cosine_similarity(w1,w2) =  [[1.]]
w1= apple , w2= pear 			 brown: cosine_similarity(w1,w2) =  [[0.78480107]]
w1= apple , w2= car 			 brown: cosine_similarity(w1,w2) =  [[0.60593385]]
w1= apple , w2= house 			 brown: cosine_similarity(w1,w2) =  [[0.50023335]]
w1= apple , w2= building 			 brown: cosine_similarity(w1,w2) =  [[0.72100234]]
w1= pear , w2= apple 			 brown: cosine_similarity(w1,w2) =  [[0.78480107]]
w1= pear , w2= pear 			 brown: cosine_similarity(w1,w2) =  [[1.]]
w1= pear , w2= car 			 brown: cosine_similarity(w1,w2) =  [[0.6408107]]
w1= pear , w2= house 			 brown: cosine_similarity(w1,w2) =  [[0.53352976]]
w1= pear , w2= building 			 brown: cosine_similarity(w1,w2) =  [[0.80650854]]
w1= car , w2= apple 			 brown: cosine_similarity(w1,w2) =  [[0.60593385]]
w1= car , w2= pear 			 brown: cosine_similarity(w1,w2) =  [[0.6408107]]
w1= car , w2= car 			 brown: cosine_similarity(w1,w2) =  [[0.99999994]]
w1= car , w2= house 			 brown: cosine_simila

In [7]:
print("MOST SIMILAR WORDS:")

for w1 in sample_words:
  print(w1," -> ",w2v_brown.wv.most_similar(w1))


MOST SIMILAR WORDS:
apple  ->  [('securely', 0.9413764476776123), ('disguised', 0.9406211972236633), ('replace', 0.9367627501487732), ('insert', 0.9365649223327637), ('thoroughly', 0.9350473284721375), ('wired', 0.9328399300575256), ('attempts', 0.9324250221252441), ('shadows', 0.9308593273162842), ('bell', 0.9287177324295044), ('portrait', 0.9278996586799622)]
pear  ->  [('gold', 0.9518222808837891), ('tax-free', 0.9494732022285461), ('outboard', 0.9452440738677979), ('formulation', 0.9446111917495728), ('enclosed', 0.9433748126029968), ('horror', 0.9431988596916199), ('bloat', 0.9427004456520081), ('drying', 0.9418098330497742), ('relief', 0.941766619682312), ('chill', 0.9416624903678894)]
car  ->  [('house', 0.9466373324394226), ('hall', 0.9047896265983582), ('room', 0.9042400121688843), ('corner', 0.9014179706573486), ('town', 0.9009864926338196), ('road', 0.8940757513046265), ('desk', 0.8921055197715759), ('bed', 0.8913705945014954), ('jig', 0.8833386898040771), ('fire', 0.8797889

## Word2Vec: Using a pre-trained model

Model trained on Google News:

Load trained model (SLIM version ~ 260 MB, one may find full version ~ 1.5GB)

In [8]:
!wget -P /root/input/ -c "https://github.com/eyaler/word2vec-slim/raw/master/GoogleNews-vectors-negative300-SLIM.bin.gz"

--2024-05-26 10:26:17--  https://github.com/eyaler/word2vec-slim/raw/master/GoogleNews-vectors-negative300-SLIM.bin.gz
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://media.githubusercontent.com/media/eyaler/word2vec-slim/master/GoogleNews-vectors-negative300-SLIM.bin.gz [following]
--2024-05-26 10:26:17--  https://media.githubusercontent.com/media/eyaler/word2vec-slim/master/GoogleNews-vectors-negative300-SLIM.bin.gz
Resolving media.githubusercontent.com (media.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to media.githubusercontent.com (media.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 276467217 (264M) [application/octet-stream]
Saving to: ‘/root/input/GoogleNews-vectors-negative300-SLIM.bin.gz’

GoogleNews-vectors- 100%[============

In [9]:
!ls /root/input

GoogleNews-vectors-negative300-SLIM.bin.gz


In [10]:
!file /root/input/GoogleNews-vectors-negative300-SLIM.bin.gz

/root/input/GoogleNews-vectors-negative300-SLIM.bin.gz: gzip compressed data, was "GoogleNews-vectors-negative300-SLIM.bin", last modified: Wed Sep 14 17:08:49 2016, max compression, original size modulo 2^32 362017275


In [11]:
EMBEDDING_FILE = '/root/input/GoogleNews-vectors-negative300-SLIM.bin.gz'
w2v_google = KeyedVectors.load_word2vec_format(EMBEDDING_FILE, binary=True)

In [12]:
print("dim = ", len(w2v_google["apple"]))

dim =  300


In [13]:

for w1 in sample_words:
  for w2 in sample_words:

    print("w1=",w1,", w2=",w2,"\t\t\t  cosine_similarity(w1,w2) = ", cosine_similarity([w2v_google[w1]],[w2v_google[w2]]))

w1= apple , w2= apple 			  cosine_similarity(w1,w2) =  [[0.9999999]]
w1= apple , w2= pear 			  cosine_similarity(w1,w2) =  [[0.64506966]]
w1= apple , w2= car 			  cosine_similarity(w1,w2) =  [[0.12830707]]
w1= apple , w2= house 			  cosine_similarity(w1,w2) =  [[0.05334292]]
w1= apple , w2= building 			  cosine_similarity(w1,w2) =  [[0.01450158]]
w1= pear , w2= apple 			  cosine_similarity(w1,w2) =  [[0.64506966]]
w1= pear , w2= pear 			  cosine_similarity(w1,w2) =  [[1.]]
w1= pear , w2= car 			  cosine_similarity(w1,w2) =  [[0.10614194]]
w1= pear , w2= house 			  cosine_similarity(w1,w2) =  [[0.07710931]]
w1= pear , w2= building 			  cosine_similarity(w1,w2) =  [[-0.00473523]]
w1= car , w2= apple 			  cosine_similarity(w1,w2) =  [[0.12830707]]
w1= car , w2= pear 			  cosine_similarity(w1,w2) =  [[0.10614194]]
w1= car , w2= car 			  cosine_similarity(w1,w2) =  [[1.0000001]]
w1= car , w2= house 			  cosine_similarity(w1,w2) =  [[0.39060056]]
w1= car , w2= building 			  cosine_similarity

In [14]:
print("MOST SIMILAR WORDS:")

for w1 in sample_words:
  print(w1," -> ",w2v_google.most_similar(w1))


MOST SIMILAR WORDS:
apple  ->  [('apples', 0.7203598618507385), ('pear', 0.6450697183609009), ('fruit', 0.6410147547721863), ('berry', 0.6302294135093689), ('pears', 0.613396167755127), ('strawberry', 0.605826199054718), ('peach', 0.6025873422622681), ('potato', 0.5960935354232788), ('grape', 0.5935865640640259), ('blueberry', 0.5866668224334717)]
pear  ->  [('pears', 0.7719404101371765), ('apricot', 0.7096841335296631), ('apricots', 0.6913131475448608), ('nectarine', 0.6751577854156494), ('almond', 0.6685435771942139), ('berry', 0.6649978160858154), ('cherries', 0.66241854429245), ('asparagus', 0.6483862400054932), ('apple', 0.6450697183609009), ('melon', 0.6406576037406921)]
car  ->  [('vehicle', 0.7821096181869507), ('cars', 0.7423830032348633), ('SUV', 0.7160962820053101), ('minivan', 0.6907036304473877), ('truck', 0.6735790371894836), ('Car', 0.6677609086036682), ('Jeep', 0.6511331796646118), ('scooter', 0.638153076171875), ('sedan', 0.6336702108383179), ('motorcycle', 0.625605404

**Germany - Berlin + Paris = ?**

In [15]:
print("Germany - Berlin + Paris in 'GoogleNewsSLIM': ",w2v_google.most_similar(positive=['Paris','Germany'], negative=['Berlin'], topn = 1))

Germany - Berlin + Paris in 'GoogleNewsSLIM':  [('France', 0.7884092926979065)]


**Germany - Berlin + Warsaw = ?**

In [16]:
print("Germany - Berlin + Warsaw in 'GoogleNewsSLIM': ",w2v_google.most_similar(positive=['Warsaw','Germany'], negative=['Berlin'], topn = 1))

Germany - Berlin + Warsaw in 'GoogleNewsSLIM':  [('Poland', 0.7386027574539185)]


# Classification of posts from dataset `20newsgroups`

In [30]:
from sklearn.datasets import fetch_20newsgroups

# Wczytanie danych treningowych
newsgroups_data = fetch_20newsgroups(subset='all', shuffle=True, random_state=42)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(newsgroups_data.data, newsgroups_data.target, test_size=0.25, random_state=42)

In [31]:


label_names = newsgroups_data.target_names

# Wyświetlenie przykładowych danych
print("label_names = ",label_names)
print("len(label_names) = ",len(label_names))

print("\nSample post (from training set): id=0")
print("Post class = ",y_train[0], " -> ", label_names[y_train[0]])
print("\n POST: \n", X_train[0])

label_names =  ['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
len(label_names) =  20

Sample post (from training set): id=0
Post class =  8  ->  rec.motorcycles

 POST:  Subject: Re: Ed must be a Daemon Child!!
From: REE700A@MAINE.MAINE.EDU
 <1993Apr2.003029.1962@adobe.com><1993Apr2.163021.17074@linus.mitre.org>
Organization: University of Maine System
Lines: 8

Ed's heading out on the highway?

Did he finally buy a bike or is he a passanger?

Jeff Andle   DoD #3005  1976 KZ900     REE700A@MAINE.MAINE.EDU

IntermittentNet access arranged through Bowdoin College.  Please reply
via e-mail, since a followup might expire before I see the Net again.


#Q10.1

* Perform PCA to $d=2$ and $d=3$ (plot results) of `x_train` using represantation  `BagOfWords` and `word2vec`, plot each class with different color.



#Q10.2
* Compare `BagOfWords` and `word2vec` in classifcation task. Train some   classifier on `x_train, y_train`, check results (accuracy) on `x_test, y_test`.
* You may compare several classifiers
* Try with and without stemming
